<?php



function html_title_parse_defaults() {
  $defaults = split(",",variable_get('html_title_defaults'));
  for($i = 1;$i<count($defaults);$i++) {
    $defaults[$i] = trim($defaults[$i]);
  }
  return $defaults;
}

function html_title_preprocess_page(&$variables) {
   $variables['title'] = filter_xss($variables['node']->title,html_title_parse_defaults());
}

function html_title_permission() {
    return array(
        'administer html_title' => array(
          'title' => t('Administer HTML Title'),
          'description' => t('Allow user edit allowed HTML tags'),
        ),
      );
}

function html_title_menu() {

  $items['admin/config/services/html_title'] = array(
      'title'=> t('HTML in titles'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('html_title_admin'),
      'access arguments' => array('administer html_title'),
      'weight'=>50,
      'type' => MENU_NORMAL_ITEM
   );

  return $items;
}

function html_title_admin() {
  static $defaults = 'sup,sub';
  $form['html_title_defaults'] = array(
    '#type' => 'textarea',
      '#title' => t('Allowable HTML tags'),
      '#default_value' => variable_get('html_title_defaults', $defaults),
      '#required' => TRUE,
      '#description' => t('comma-separated list of allowed HTML tags in titles')
      );
  return system_settings_form($form); 
}
